title: Lemmethink
email: tinysnippets@gmail.com
description: >-
  Hello world!
  

baseurl: ""
url: ""
github_username:  magniff

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
